version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME: "https://localhost"
      KC_HTTPS_PORT: "8443"
      KC_HTTPS_CERTIFICATE_FILE: "/etc/keycloak/certs/tls.crt"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/etc/keycloak/certs/tls.key"
    ports:
      - "443:8443"
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
      - ./keycloak/certs:/etc/keycloak/certs:ro
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: registry.redhat.io/rhel10/postgresql-16
    container_name: postgres
    environment:
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_USER: keycloak
      POSTGRESQL_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  quarkus-app:
    build:
      context: ./quarkus-app
      dockerfile: Dockerfile
    container_name: quarkus-app
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - keycloak

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache-proxy
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - quarkus-app
      - keycloak
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

