version: '3.8'

# This compose file is for Apache connecting directly to Entra ID (without Keycloak)
# Keycloak and PostgreSQL services are not required for this configuration

services:
  quarkus-app:
    build:
      context: ./quarkus-app
      dockerfile: Dockerfile
    container_name: quarkus-app
    ports:
      - "8081:8080"
    networks:
      - app-network

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache-proxy
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - quarkus-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

